version: '3'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_USER : "SA"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - sql
    environment:
      DATABASE_URL: "jdbc:mssql://msql:1433/account-management"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Password123"
    ports:
      - "8080:8080"
    networks:
      - backend

  account-service:
    build:
      context: ./account-service
    depends_on:
      - sql
    environment:
      DATABASE_URL: "jdbc:mssql://msql:1433/account-management"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Password123"
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge

